name: Manually Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g. production, staging)'
        required: true
        default: 'staging'
jobs:
  prepare-env:
    uses: your-repo/.github/workflows/amplify_deploy.yml@main
    outputs:
      app_env_name: ${{ steps.set-output.outputs.app_env_name }}

    steps:
    - name: Combine repo name and environment
      id: set-output
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        APP_ENV_NAME="${REPO_NAME}-${{ github.event.inputs.environment }}"
        echo "app_env_name=$APP_ENV_NAME" >> $GITHUB_ENV

  call-deploy:
    needs: prepare-env
    steps:
      uses: your-repo/.github/workflows/amplify_deploy.yml@main
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        environmentName: ${{ needs.prepare-env.outputs.app_env_name }}
